Create maps for social values Decision Point Article
========================================================



```{r import data}
  rm(list=ls())
  packages(raster)
  packages(fields)
  packages(maptools)
  packages(reshape)
  packages(ggplot2)
#   packages(dplyr)
  packages(png)
  packages(rasterVis)
  packages(scales)
  packages(ggmap)
  packages(colorRamps)
  
  computer <- "//654cw-20990/Amy"

# define paths for input and output files
input_path <- paste0(computer,'/GIS_data/Perth-Peel/zonation/100m/PP/')
output_path <- paste0(computer,'/GIS_data/Perth-Peel/zonation/100m/PP/')

colours <- d(colour=c("#87CC66","#7AB6F5","#2AFFD5","#C83737","#FF9955","#B380FF","#C87137","#008080"),scenario=c("1. Biological","3. Social","4. Biological & Social","5. Development","6. Biological & Development","8. Social & Development", "9. Biological, Social & Development","10. Integrating Biological\n& Social Values"),value=c(1,3,4,5,6,8,9,10)) 


```

```{r raster plotting theme}

theme_raster <- function (base_size = 12, base_family = "") 
{
    theme_bw(base_size = base_size, base_family = base_family) %+replace% 
        theme(axis.text = element_text(size = rel(0.8)), 
              axis.ticks = element_blank(),
              panel.background = element_rect(fill = "transparent",colour = NA),
              panel.grid = element_blank(),
              panel.border=element_blank(),
              plot.background = element_rect(fill = "transparent",colour = NA),
              axis.title = element_blank(),
              axis.text  = element_blank(),
              legend.position="none")
}

```


```{r import curve data}
species.impacts <- read.csv(paste0(input_path,"species_of_interest.csv"))

plot.species <- species.impacts[1:3,c(1,2,4,5,6,7)]

plot.30 <- melt(plot.species,id="Scenario")
colnames(plot.30) <- c("scenario","species","impact")
plot.30$scenario <- factor(plot.30$scenario, levels=c("3. EIA3 (Option 1)", "2. EIA2","1. EIA1"))
  plot.30$species <- gsub("_"," ",plot.30$species)
  plot.30$species <- gsub(".leaved","-leaved",plot.30$species)
  plot.30$species <- gsub("\\.","\\'",plot.30$species)

  print(species.plot <- {
    ggplot(plot.30, aes(species, impact, fill = scenario)) + geom_bar(stat="identity", position = "dodge") + 
    ylab("Proportion of distribution lost") +
    coord_flip() +
    theme_bw() +
#      scale_fill_manual(values=as.character(colours$colour[c(8,2,1)]),breaks=c("Biological values only","Social values only","Integrated solution")) + 
    theme(axis.ticks.x = element_blank()) + 
    theme(panel.background = element_blank(),panel.grid.minor = element_blank(),panel.grid.major.y = element_blank(),panel.border=element_blank()) +  
    theme(axis.title.y = element_blank(),axis.ticks.y = element_blank(),axis.text.y  = element_text(hjust=1, size=14)) + 
    theme(axis.title.x = element_text(vjust=0,size=15), axis.text.x = element_text(size=12)) +
    theme(legend.title=element_blank(), legend.position="none", legend.text = element_blank(),legend.key=element_blank())
    })

ggsave(paste0(output_path,"species_impacts.png"),species.plot, width=7.5,height=6,dpi=300)



```

