---
title: "summarise maxent outputs for DotE report"
author: "Amy Whitehead"
date: "Wednesday, October 29, 2014"
output: html_document
---



```{r}
rm(list=ls())

# computer <- "~" #My computer
#computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

source("C:/Users/awhitehead/Dropbox/Random R code/rbind.columns.r")

# define paths for input and output files
maxent.dir <- paste0(computer,'/GIS_data/Perth-Peel/Maxent_files/environmental_data/100m/ibra/output/')

taxa <- c("birds","mammals","plants","reptiles","invertebrates")


```


```{r extract maxent results}
envi.parameters <- c("Species", "X.Training.samples","Test.AUC","mean_temp",  "hot_temp",	"cold_temp",	"mean_rain",	"seasonal_rain",	"mean_solar",	"altitude",	"slope",	"eastness",	"rugg500",	"terr_1000",	"nvis_mvs_exotics",	"Banksia2000",	"Eucalyptus2000",	"grassland2000",	"Melaleuca2000",	"pines2000",	"Woody2000",	"water_dist_perm",	"water_dist_perm_ephem",	"soilAtlas2M",	"clay",	"fert")

for (i in seq(taxa)){
  maxentResults <- read.csv(paste0(maxent.dir,taxa[i],"/Model3/MaxentResults.csv"))
    maxentResults <- maxentResults[grepl("average",maxentResults$Species),]
  parameters <- c("Species","X.Training.samples","Test.AUC","AUC.Standard.Deviation",names(maxentResults[grepl("permutation.importance",names(maxentResults))]))
  
  maxentResults <- maxentResults[,names(maxentResults) %in% as.character(parameters)]
  
  names(maxentResults) <- gsub("X_|.permutation.importance","",names(maxentResults))

maxentResults$Species <- gsub("_"," ",gsub(" \\(average\\)","",maxentResults$Species))
maxentResults <- maxentResults[order(maxentResults$Species),]
maxentResults[,4:ncol(maxentResults)] <- round(maxentResults[,4:ncol(maxentResults)],2)
 maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
maxentResults <- maxentResults[,envi.order]
assign(paste0(taxa[i],"_MR"),maxentResults)
 write.csv(maxentResults,paste0(maxent.dir,taxa[i],"_DotE report - maxent summary.csv"),row.names=F) 
}

# output <- rbind.columns(birds_MR,mammals_MR)
#   output <- rbind.columns(output,plants_MR)
#   output <- rbind.columns(output,reptiles_MR)
#   output <- rbind.columns(output,invertebrates_MR)
# 
# names(output) <- gsub("X|.permutation.importance","",names(output))
# 
# output$Species <- gsub("_"," ",gsub(" \\(average\\)","",output$Species))
# output <- output[order(output$Species),]
# output[,4:ncol(output)] <- round(output[,4:ncol(output)],2)
#  output$Test.AUC <- paste0(round(output$Test.AUC,3)," (",round(output$AUC.Standard.Deviation,3),")")
# output <- output[,!names(output) %in% "AUC.Standard.Deviation"]
# 
# write.csv(output,paste0(maxent.dir,"DotE report - maxent summary.csv"),row.names=F)

```
