---
title: "Calculate CL development impacts"
author: "Amy Whitehead"
date: "Monday, July 28, 2014"
output: html_document
---


```{r set up}
rm(list=ls())
library(raster)
library(maptools)
library(colorRamps)
library(fields)
library(RColorBrewer)
library(reshape)
library(ggplot2)

  GDA94.50 <- CRS("+proj=utm +zone=50 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# computer
# computer <- "~"
#computer <- "//654cw-20990/Amy"
computer <- "E:/Super Computer Data"

# define paths for input and output files
input_path <- paste0(computer,'/GIS_data/Perth-Peel/zonation/100m/')
output_path <- paste0(computer,'/GIS_data/Perth-Peel/zonation/100m/Conservation_Letters/final/output/')

# import biodiversity feature names
  names <- as.vector(read.table(paste0(input_path,'cl.ppsa.rank.spp'), header=F, sep='\t')[,6])

# date of the output files
#   analysis.date <- '20140728' # remember to update to correct date
  analysis.date <- '20160112'

  save.plots <- TRUE
  
  load(paste0(output_path,"Analysis of Zonation runs from ",analysis.date,".Rdata"))

```

```{r useful functions}
  
  trim <- function (x) gsub("^\\s+|\\s+$", "", x)
  clean.names <- function (x) trim(gsub("_"," ",gsub("PP|\\.tif|SSI\\.|\\/", "", x)))
  clean.scenarios <- function (x) trim(gsub(output_path,"", gsub(paste0("_",analysis.date),"", gsub("CL\\.|\\.CAZ_ME\\.curves\\.txt$|\\.CAZ_E\\.curves\\.txt","",x))))
  
```


```{r colour palettes}
map.background <- "whitesmoke"

pa.colours <- d(label=c("Level 3","Level 2","Level 3","Priority protected","Priority unprotected"),colour=c("#78c679","#31a354","#006837","#a6611a","grey40"),stringsAsFactors = F)

dev.colours <- d(label=c("Existing","Proposed","Cleared","Retained"),colour=c("grey60","#fdae61","#d7191c","#2c7bb6"),stringsAsFactors = F)

# colours for the curves plots - Heini
# col.all <- c('dark grey', 'skyblue2', 'skyblue4', 'darkolivegreen3', 'darkolivegreen4')
# col.nonmnes <- c('lightskyblue4', 'skyblue2', 'steelblue', 'dodgerblue3', 'dodgerblue4')
# col.mnes <- c('rosybrown4', 'lightcoral', 'indianred', 'brown1', 'red4')

# colours for the curves plots - Amy
col.all <- c("grey60",brewer.pal(4,"Set1"))
col.nonmnes <- brewer.pal(9,"Blues")[4:9]
col.mnes <- brewer.pal(9,"Reds")[4:9]

pri.col = c('dark grey', 'turquoise', 'yellow', 'orange', 'red')
pa.col = c('palegreen3', 'palegreen4')
pri.breaks = c(0,0.7,0.85,0.9,0.95,1)
leg.labels <- c("top 5%","top 10%","top 15%","top 30%","rest")

```

```{r import curve data}
# LH General impact assessment

# get names of Zonation curves-files (you can also do this manually)
files <- grep('.curves.txt', list.files(output_path), value=T)
  files <- files[grep(analysis.date,files)]
  files <- files[!grepl("baseline",files)] # remove baseline scenario & scenarios with protected areas

# check for species that have zero observations at the start of the prioritisation
  baseline.curves <- read.table(paste0(output_path,"CL.baseline_",analysis.date,".CAZ_E.curves.txt"), skip=1, header=F, sep='')
      colnames(baseline.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', names)
  zero.obs <- baseline.curves[1,8:ncol(baseline.curves)]
    names(zero.obs[which(zero.obs==0)])

# when does the first species go extinct in the baseline scenario?
  extinct <- baseline.curves[baseline.curves$min_prop_rem==0,][1,]
    cat("First species goes extinct at step",row.names(extinct), "with",extinct$Prop_landscape_lost*100, "% removed","\n")
   names(extinct[which(extinct==0)])
  
# % species distributions in top fractions
  baseline.sp.dist <- d(top.fraction=c(0.05,0.1,0.3),mean=NA,se=NA,min=NA,worst.sp=NA,n.sp.25=NA)
  
for(i in seq(baseline.sp.dist$top.fraction)){
    baseline.sp.dist$mean[i] <- baseline.curves$ave_prop_rem[baseline.curves$Prop_landscape_lost>=(1-baseline.sp.dist$top.fraction[i])][1]
#    baseline.sp.dist$se[i] <- round(se(t(baseline.curves[baseline.curves$Prop_landscape_lost>=(1-baseline.sp.dist$top.fraction[i]),8:ncol(baseline.curves)][1,])),3)
    x <- as.vector(baseline.curves[baseline.curves$Prop_landscape_lost>=(1-baseline.sp.dist$top.fraction[i]),8:ncol(baseline.curves)][1,])
    baseline.sp.dist$se[i] <- round(sd(x)/sqrt(length(x)),3)
    baseline.sp.dist$min[i] <- baseline.curves$min_prop_rem[baseline.curves$Prop_landscape_lost>=(1-baseline.sp.dist$top.fraction[i])][1]
    z <- data.frame(baseline.curves[baseline.curves$Prop_landscape_lost>=(1-baseline.sp.dist$top.fraction[i]),8:ncol(baseline.curves)][1,])
    baseline.sp.dist$worst.sp[i] <- clean.names(names(z[which(z==min(z))]))
    baseline.sp.dist$n.sp.25[i] <- length(which(z<0.25))
}
  
  write.csv(baseline.sp.dist,paste0(output_path,"tables/CL_baseline_priorities_",analysis.date,".csv"),row.names = F)

```

```{r identify cleared area}
# how much area is cleared in each impact scenario?
# import scenario rasters
      scenario.files <- dir(paste0(input_path,"Conservation_Letters/final/scenarios/"),pattern=".tif$",full.names=T)
      scenarios <- stack(scenario.files)
      scenario.names <- names(scenarios)
      
tryCatch({
  cleared_area <- read.csv(paste0(output_path,"tables/CL_cleared_area_",analysis.date,".csv"))
  }, error = function(err){
  
      cleared_area <- data.frame(scenario=scenario.names,cleared=NA,cleared.ha=NA,protected=NA,protected.ha=NA,total=NA)

        for(i in 1:nlayers(scenarios)){
          r <- scenarios[[i]]
          cleared_area$total[i] <- length(r[!is.na(r)])
          cleared_area$cleared.ha[i] <- length(r[r<=2])
          cleared_area$cleared[i] <- cleared_area$cleared.ha[i]/cleared_area$total[i]
          cleared_area$protected.ha[i] <- length(r[r>3])
          cleared_area$protected[i] <- cleared_area$protected.ha[i]/cleared_area$total[i]
          cat(names(r),"\n")
        }
      
  
        write.csv(cleared_area,paste0(output_path,"tables/CL_cleared_area_",analysis.date,".csv"), row.names = F)
  })
      
  cleared_area <- read.csv(paste0(output_path,"tables/CL_cleared_area_",analysis.date,".csv"))

```

```{r produce baseline priority map}

  zonation_priority <- raster(paste0(output_path,"CL.baseline_",analysis.date,".CAZ_E.rank.compressed.tif"))
  
  PP.mask <- raster(paste0(computer,"/GIS_Data/Perth-Peel/mask files/perth.mask.tif"))
  PP.clipping.mask <- zonation_priority
    PP.clipping.mask[!is.na(PP.clipping.mask)] <- 0
  PP.shp <- readShapePoly(paste0(computer,"/GIS_data/Perth-Peel/DOP/DoP_StrategicAssessmentStudyBoundary_Extended_20121004_GDA94.shp"), proj4=GDA94)
    PP.shp <- spTransform(PP.shp,GDA94.50)

  IsBecomes.zonation <- matrix(c(0,0.50,1, 0.50,0.70,2,0.70,0.85,3,0.85,0.90,4,0.90,0.95,5,0.95,1.00,6), ncol=3, byrow=TRUE)
    
  reclassified.zonation <- reclassify(zonation_priority,IsBecomes.zonation)
  
  leg.labels <- c("top 5%","top 10%","top 15%","top 30%","top 50%","rest")
  breaks <- c(0,0.2,0.5,0.75,0.9,0.95,0.98,1)
  colours <- c("black","dark blue","blue","yellow","magenta","dark red", "red")
  
  top.30 <- zonation_priority
    top.30[top.30 < 0.7] <-NA
    top.30[!is.na(top.30)] <- 1

  if(save.plots==TRUE){
    
    png(paste0(output_path,"figures/zonation.legend.png"),height=5,width=3,units="cm",res=300, bg="transparent")
    par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
    image.plot( legend.only=TRUE, zlim= c(0,1), breaks=c(0,0.5,0.7,0.85,0.9,0.95,1),col=blue2red(6),axis.args=list( at=c(0,1), labels=c("Low","High")))
    dev.off()
    
    png(paste0(output_path,"figures/zonation_priority.png"),height=10,width=7,units="cm",res=300, bg="transparent")
    par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
    plot(PP.mask,col=map.background,legend=F,box=F,axes=F,zlim=c(1,7))
      plot(zonation_priority,col=blue2red(100),add=T,legend=F)
      plot(PP.shp, add=T, lwd=0.5)
    #   image.plot(legend.only=TRUE,smallplot=c(.85, .87, .35, .55),legend.width=0.75,legend.shrink=0.25, zlim= c(0,1), nlevel=100, col=blue2red(100),axis.args=list(at=c(0,1), labels=c("Low","High"), cex.axis=0.6),legend.args=list(text='Conservation priority', side=4, font=2, line=2.5, cex=0.7)) 
    #   scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
    dev.off()
    
    png(paste0(output_path,"figures/classified_zonation_priority.png"),height=10,width=7,units="cm",res=300, bg="transparent")
    par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
    plot(PP.mask,col=map.background,legend=F,box=F,axes=F,zlim=c(1,7))
      plot(reclassified.zonation,col=blue2red(6),add=T,legend=F)
      plot(PP.shp, add=T, lwd=0.5)
    #   legend("bottomright",leg.labels,col=rev(blue2red(7)),pch=15,bty="n",title="Conservation priority",cex=0.7)
    #   scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
    dev.off()
    png(paste0(output_path,"figures/top30_raster.png"),height=10,width=7,units="cm",res=300, bg="transparent")
    par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
    plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
      plot(top.30,col="darkgreen",legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
    #   scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
    dev.off()
    
    
    png(paste0(output_path,"figures/priority_top30_raster.png"),height=14,width=15,units="cm",res=300, bg="transparent")
    par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
    plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F,zlim=c(1,7))
      plot(zonation_priority,col=blue2red(100),add=T,legend=F)
      plot(PP.shp, add=T, lwd=0.5)
      image.plot(legend.only=TRUE,smallplot=c(.85, .87, .35, .55),legend.width=0.75,legend.shrink=0.25, zlim= c(0,1), nlevel=100, col=blue2red(100),axis.args=list(at=c(0,1), labels=c("Low","High"), cex.axis=0.6),legend.args=list(text='Conservation priority', side=4, font=2, line=2.5, cex=0.7)) 
      mtext("a)",side=3,line=-1,adj=0,cex=0.8)
    #   scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
    
    plot(PP.mask,col=map.background,legend=F,box=F,axes=F)
      plot(top.30,col="darkgreen",legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
      mtext("b)",side=3,line=-1,adj=0,cex=0.8)
    dev.off()

     png(paste0(output_path,"figures/priorities.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
     par(mar=c(0.25,1.5,0.25,4), oma=c(0,0,0,0))
     plot(zonation_priority,col=pri.col,breaks=pri.breaks,legend=F,box=F,axes=F)
      plot(PP.shp, add=T, lwd=0.5)
    legend('topright', inset=c(-0.20,0), leg.labels, col="black",fill=rev(pri.col), bty="n", title="Conservation priority", cex=1, xpd=NA)
    #   scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
    dev.off()
    
}

```

```{r whats already protected}
# calculate the area currently protected
  protected.curves <- read.table(paste0(output_path,"CL.protected_areas_",analysis.date,".CAZ_ME.curves.txt"), skip=1, header=F, sep='')
      colnames(protected.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', names)

  protected.index <- which(grepl("protected.areas",names(scenarios))==TRUE)
  protected.areas <- scenarios[[protected.index[1]]]
  protected.areas.clipped <- scenarios[[protected.index[2]]]
  
  PAs <- protected.areas.clipped
  PAs[PAs==3] <- NA


protected.table <- data.frame(scenario=c("protected.areas","protected.areas1","protected.areas2","protected.areas3"),security.level=c("All","High","Medium","Low"),area=NA,protected.priorities=NA,mean.dist=NA,area.cum=NA,protected.priorities.cum=NA,n.sp.cum=NA,mean.zonation.cum=NA,min.zonation.cum=NA,protected.vegetation.cum=NA,protected.vegetation=NA,mean.dist.cum=NA,min.dist=NA,se.dist=NA,raster.value=c(3,6,5,4)) 

for(h in seq(protected.table$scenario)){
# extract cleared area from clipped scenario
    if(h == 1) {
    protected <- cleared_area$protected.ha[cleared_area$scenario=="protected.areas"]
    protected.vegetation <- cleared_area$protected[cleared_area$scenario=="protected.areas_clipped"]
    PAs <- protected.areas.clipped
      PAs[PAs==3] <- NA 
    } else {
      protected <- length(protected.areas[protected.areas>=protected.table$raster.value[h]])
      protected.vegetation <- length(protected.areas.clipped[protected.areas.clipped>=protected.table$raster.value[h]])/length(protected.areas.clipped[!is.na(protected.areas.clipped)])
      PAs <- protected.areas.clipped
        PAs[PAs!=protected.table$raster.value[h]] <- NA 
    }
    a <- protected.curves[which(protected.curves$Prop_landscape_lost>(1-protected.vegetation))[1],] # first line greater than cleared area - conservative
    #a <- curves[which.min(abs(curves$Prop_landscape_lost-cleared)),] # line closest in value to cleared area
    
    # calculate impacts
    protected.table$area[h] <- protected
      protected.table$area.cum[h] <- protected.table$area[h]
    protected.table$protected.vegetation[h] <- round(protected.vegetation*100,2)
      protected.table$protected.vegetation.cum[h] <- protected.table$protected.vegetation[h]
    protected.table$protected.priorities[h] <- round(length(top.30[PAs])/length(top.30)*100,2)
      protected.table$protected.priorities.cum[h] <- protected.table$protected.priorities[h]
    protected.table$mean.dist[h] <- round(a[, 4]*100,2)
      protected.table$mean.cum.dist[h] <- protected.table$mean.dist[h]
    protected.table$min.dist[h] <- round(a[, 3]*100,2)
      protected.table$min.dist.cum[h] <- protected.table$min.dist[h]
    
    if(h>=3){
      protected.table$area[h] <- protected.table$area.cum[h] - protected.table$area.cum[h-1]
      protected.table$protected.vegetation[h] <- protected.table$protected.vegetation.cum[h] - protected.table$protected.vegetation.cum[h-1]
      protected.table$mean.dist[h] <- protected.table$mean.dist.cum[h] - protected.table$mean.dist.cum[h-1]
      protected.table$protected.priorities.cum[h] <- protected.table$protected.priorities.cum[h] + protected.table$protected.priorities.cum[h-1]
      
    }

# how would zonation do with the same area?    
    z <- baseline.curves[which(baseline.curves$Prop_landscape_lost>(1-protected.vegetation))[1],] # first line greater than cleared area - conservative
    protected.table$mean.zonation.cum[h] <- round(z[, 4]*100,2)
    protected.table$min.zonation.cum[h] <- round(z[, 3]*100,2)
 # subset a to just keep species distribution data
    a <- a[,8:ncol(a)]
    
    if(h==1){
      unprotected.sp <- clean.names(colnames(a[which(a==0)]))
    }

    protected.table$se.dist[h] <- round(se(t(a))*100,2)
    protected.table$n.sp.cum[h] <- length(which(a == 0))
 }

  write.csv(protected.table,paste0(output_path,"tables/CL_protected.table_",analysis.date,".csv"),row.names = F)

# load horrenda table
  protected.species <- read.csv(paste0(computer,"/GIS_data/Perth-Peel/species data/WA listed protected species.csv"))

  # at risk species
  unprotected.species <- protected.species[protected.species$Scientific.Name %in% unprotected.sp, c("Scientific.Name","AcceptedCommonName","Taxa","mnes","WA_Status","EPBC_Status","Endemism","datatype","EPBC_ListedMigratory",	"EPBC_ListedMarine")]
    for(i in 1:ncol(unprotected.species)){
      unprotected.species[,i] <- as.character(unprotected.species[,i])
    }  
  
    unprotected.species$AcceptedCommonName[grepl("unknown",unprotected.species$AcceptedCommonName)] <- ""
    unprotected.species$mnes[is.na(unprotected.species$mnes)] <- ""
    
    status <- colnames(unprotected.species[grepl("Status",colnames(unprotected.species))])
    
    for(i in seq(status)){
      unprotected.species[grepl("listed",unprotected.species[,status[i]]),status[i]] <- ""
      unprotected.species[grepl("Critically Endangered",unprotected.species[,status[i]]),status[i]] <- "CE"
      unprotected.species[grepl("Endangered",unprotected.species[,status[i]]),status[i]] <- "E"
      unprotected.species[grepl("Vulnerable",unprotected.species[,status[i]]),status[i]] <- "V"
      if(i==2) {
        unprotected.species[grepl("yes",unprotected.species$EPBC_ListedMarine),status[i]] <- paste0(unprotected.species[grepl("yes",unprotected.species$EPBC_ListedMarine),status[i]], ", Marine")
        unprotected.species[grepl("yes",unprotected.species$EPBC_ListedMigratory),status[i]] <- paste0(unprotected.species[grepl("yes",unprotected.species$EPBC_ListedMigratory),status[i]], ", Migratory")
      }
    }
    
    unprotected.species$EPBC_Status <- gsub("^\\,\\s", "",unprotected.species$EPBC_Status)
      # unprotected.species$EPBC_Status[grepl("Sandpiper|Tern",unprotected.species$AcceptedCommonName)] <- "Migratory"
    unprotected.species$Taxa <- gsub("\\b(\\w)","\\U\\1",gsub("tec","TEC",gsub("s","",unprotected.species$Taxa)), perl=TRUE)
    
    unprotected.species <- unprotected.species[,c("Scientific.Name","AcceptedCommonName","Taxa","mnes","WA_Status","EPBC_Status","Endemism","datatype")]
    
    colnames(unprotected.species) <- c("Biodiversity.Feature","Common.Name","Taxa","MNES","WA.Status","EPBC.Status","Endemism","Data.Type")

  write.csv(unprotected.species, paste0(output_path, 'tables/TableD2_CL_unprotected_species_',analysis.date,'.csv'), row.names=F)
  
```


```{r make scenario maps & assess conflicts}

  development <- c("scenario1_urban","scenario2_industrial","scenario3_ruralres","scenario4_infrastructure","scenario5_pines","scenario6_brm","scenario7_cumulative","scenario1_1_eia1","scenario1_2_eia2", "scenario1_3a_eia3_option1", "scenario1_3b_eia3_option2", "scenario1_4_development_footprint","scenario1_1_eia1_existing","scenario1_2_eia2_existing", "scenario1_3a_eia3_option1_existing", "scenario1_3b_eia3_option2_existing", "scenario1_4_development_footprint_existing","coa.urban.no.existing", "CL_EIA1","CL_EIA2","CL_EIA3O1","CL_EIA3O2","CL_EIA4","scenario_cumulative1","scenario_cumulative2","scenario_cumulative3")
  dev.label <- c("1. Urban","2. Industrial","3. Rural Residential", "4. Infrastructure", "5. Forestry", "6. Mining", "7. Cumulative","1.1 EIA1","1.2 EIA2", "1.3a EIA3 Option1", "1.3b EIA3 Option2", "1.4 Development Footprint","1.1 EIA1 existing","1.2 EIA2 existing", "1.3a EIA3 Option1 existing", "1.3b EIA3 Option2 existing", "1.4 Development Footprint existing","1a. Urban","EIA1","EIA2","EIA3O1","EIA3O2","EIA4","Cumulative V1","Cumulative V2", "Cumulative V3")

  conflict.table <- data.frame(scenario=dev.label,top.conflict.area=NA,protected.conflict.area=NA,prop.dev.t30=NA,prop.dev.pa=NA,prop.top=NA,prop.protected=NA,prop.protected1=NA,prop.protected2=NA,prop.protected3=NA, mask.layer=development)
  # conflict.table <- conflict.table[order(conflict.table$scenario),]

 for (i in seq(development)){
  cat("Calculating conflicts for",dev.label[i],"\n")
  r <- scenarios[[which(names(scenarios) %in% development[i]==TRUE)]]
    r[r==3] <- NA
         
#    png(paste0(output_path,development[i],".png"),height=10,width=7,units="cm",res=300, bg="transparent")
#     par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))   
#     
#     plot(PP.clipping.mask,col="grey90",legend=F,box=F,axes=F)
#       plot(r,col="grey30",add=T,legend=F)
#       plot(PP.shp, add=T, lwd=0.5)
# #     mtext(dev.label[i],side=3,line=-1.5,adj=0.85,cex=0.8)
#   
#   dev.off()
 
# conflicts with the top conservation priorities
    conflict.t30 <- top.30
    conflict.t30 <- sum(r,conflict.t30)
    dev.t30 <- merge(conflict.t30,r)
#       conflict.t30[conflict.t30!=3] <- NA # evaluate conflicts only with proposed development

  # area of top 30 that conflicts with development
    conflict.table$top.conflict.area[i] <- length(conflict.t30[!is.na(conflict.t30)])
  # proportion of top 30 that conflicts with development
    conflict.table$prop.top[i] <- round(length(conflict.t30[!is.na(conflict.t30)])/length(top.30[!is.na(top.30)])*100,2)
  # proportion of development area that conflicts with development
    conflict.table$prop.dev.t30[i] <- round(length(conflict.t30[!is.na(conflict.t30)])/length(r[!is.na(r)])*100,2)

# conflicts with current protected areas
  protected.areas[protected.areas==3] <- NA
    conflict.pa <- sum(r,protected.areas)

    conflict.table$protected.conflict.area[i] <- length(conflict.pa[!is.na(conflict.pa)])
    conflict.table$prop.dev.pa[i] <- round(length(conflict.pa[!is.na(conflict.pa)])/length(r[!is.na(r)])*100,2)
    conflict.table$prop.protected[i] <- round(length(conflict.pa[!is.na(conflict.pa)])/length(protected.areas[!is.na(protected.areas)])*100,2)
    conflict.table$prop.protected1[i] <- round(length(conflict.pa[conflict.pa==7])/length(protected.areas[protected.areas==6])*100,2)
    conflict.table$prop.protected2[i] <- round(length(conflict.pa[conflict.pa==6])/length(protected.areas[protected.areas==5])*100,2)
    conflict.table$prop.protected3[i] <- round(length(conflict.pa[conflict.pa==5])/length(protected.areas[protected.areas==4])*100,2)

#   png(paste0(output_path,development[i],"_top30.conflict.png"),height=10,width=7,units="cm",res=300, bg="transparent")
#   par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
#     
#     plot(PP.clipping.mask,col="grey90",legend=F,box=F,axes=F)
#       plot(conflict.t30,col=c("red"),add=T,legend=F)
#       plot(PP.shp, add=T, lwd=0.5)
# #     mtext(dev.label[i],side=3,line=-1.5,adj=0.85,cex=0.8)
#   
#   dev.off()
# 
#   png(paste0(output_path,development[i],"_protected.areas_conflicts.png"),height=10,width=7,units="cm",res=300, bg="transparent")
#   par(mar=c(0.25,1.5,0.25,0), oma=c(0,0,0,0))
#   
#   plot(PP.clipping.mask,col="grey90",legend=F,box=F,axes=F)
#         plot(conflict.pa,col=c("red"),add=T,legend=F)
#         plot(PP.shp, add=T, lwd=0.5)
#   #     mtext(dev.label[i],side=3,line=-1.5,adj=0.85,cex=0.8)
#   
#   dev.off()
  
  png(paste0(output_path,"figures/",development[i],".png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
   par(mar=c(0.25,1.5,0.25,4), oma=c(0,0,0,0))
   plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(r,col=dev.colours$colour[1],legend=F,add=T)
     plot(PP.shp, add=T, lwd=0.5)
  dev.off()
  
  png(paste0(output_path,"figures/",development[i],"_top30_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
   par(mar=c(0.25,1.5,0.25,4), oma=c(0,0,0,0))
   plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
    plot(dev.t30,col=c(dev.colours$colour[1],"red"),legend=F,add=T)
    plot(PP.shp, add=T, lwd=0.5)
  dev.off()    
       
  r[!is.na(r)] <-1
  dev.pri <- r*zonation_priority
  
  png(paste0(output_path,"figures/",development[i],"_priority_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
   par(mar=c(0.25,1.5,0.25,4), oma=c(0,0,0,0))
   plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(dev.pri,col=pri.col,breaks=pri.breaks,legend=F,add=T)
     plot(PP.shp, add=T, lwd=0.5)
   legend('topright', inset=c(-0.20,0), leg.labels, col="black",fill=rev(pri.col), bty="n", title="Conservation priority", cex=1, xpd=NA)
    scalebar(10000,type="line",divs=3,below="",cex=0.6,label=c("","10km",""))
   dev.off()

}


write.csv(conflict.table,paste0(output_path,"tables/CL_conflict.table_",analysis.date,".csv"),row.names=F)

```

```{r assess impacts}
# create the output table
  loss.files <- files[!grepl("protected_areas",files)]
  loss.table <- as.data.frame(matrix(NA, length(loss.files), 21))
  colnames(loss.table) <- c('scenario', 'area.developed.ha','area.cleared.ha','protected.areas','priority.areas','mean.loss(%)', 'max.loss(%)','median.loss(%)','25%.sp.loss', '100%.loss', '90%.loss', '75%.loss', '50%.loss','area.developed', 'area.cleared', '100%.loss.sp', '90%.loss.sp', '75%.loss.sp', '50%.loss.sp','mask.layer','order')
    dim(loss.table)

  distribution.table <- as.data.frame(matrix(NA, length(names), length(loss.files)))
  colnames(distribution.table) <- loss.files
  distribution.table$species <- names

# match scenario with mask layer
  ## this is a bit of a hack as I didn't give them the same labels - fail
  ## need to make sure that these get updated

  loss.table$mask.layer <- gsub('.curves.txt', '', gsub(paste0("_",analysis.date,".CAZ_ME"), "",gsub("CL.","",loss.files)))
    loss.table$mask.layer <- gsub('EIA','CL_EIA',loss.table$mask.layer)
  loss.table$scenario <- c("EIA1","EIA2","EIA3O1","EIA3O2","EIA4","Cumulative V1","Cumulative V2","Cumulative V3","1.1 EIA1","1.1 EIA1 existing","1.2 EIA2","1.2 EIA2 existing", "1.3a EIA3 Option1", "1.3a EIA3 Option1 existing", "1.3b EIA3 Option2", "1.3b EIA3 Option2 existing", "1.4 Development Footprint", "1.4 Development Footprint existing", "1. Urban","2. Industrial","3. Rural Residential", "4. Infrastructure", "5. Forestry", "6. Mining", "7. Cumulative")
  loss.table$order <- c(18,19,20,21,22,23,24,25,8,13,9,14,10,15,11,16,12,17,1,2,3,4,5,6,7)
  
  # calculating impact numbers for each scenario
  for (h in 1:length(loss.files)){
    cat("calculating impact for",loss.table[h,1],"\n")
  # Name of original curves file
    input <- paste0(output_path, loss.files[h])
  
  try({
    # Upload the curves file
      curves <- read.table(input, skip=1, header=F, sep='')
        colnames(curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', names)
      
    # extract cleared area from clipped scenario
      developed <- cleared_area$cleared[cleared_area$scenario==loss.table$mask.layer[h]]
      cleared <- cleared_area$cleared[cleared_area$scenario==paste0(loss.table$mask.layer[h],"_clipped")]
      
    # identify curve data associated with cleared area
      a <- curves[which(curves$Prop_landscape_lost>cleared)[1],] # first line greater than cleared area - conservative
      #a <- curves[which.min(abs(curves$Prop_landscape_lost-cleared)),] # line closest in value to cleared area
      
      # calculate impacts
      loss.table$area.developed[h] <- round(cleared_area$cleared[cleared_area$scenario==loss.table$mask.layer[h]]*100,2)
      loss.table$area.cleared[h] <- round(cleared_area$cleared[cleared_area$scenario==paste0(loss.table$mask.layer[h],"_clipped")]*100,2)
      loss.table$area.developed.ha[h] <- cleared_area$cleared.ha[cleared_area$scenario==loss.table$mask.layer[h]]
      loss.table$area.cleared.ha[h] <- cleared_area$cleared.ha[cleared_area$scenario==paste0(loss.table$mask.layer[h],"_clipped")]
      loss.table$`mean.loss(%)`[h] <- round(100-(a[, 4]*100),2)
      loss.table$`max.loss(%)`[h] <- round(100-(a[, 3]*100),2)
      loss.table$`median.loss(%)`[h] <- round(100-(median(as.numeric(data.frame(a[,8:ncol(a)])))*100),2)
      loss.table$`25%.sp.loss`[h] <- round(100-(quantile(as.numeric(data.frame(a[,8:ncol(a)])),0.25))*100,2)
    
      # subset a to just keep species distribution data
      a <- a[,8:ncol(a)]
      distribution.table[,h] <- t(a)
      
      loss.table$`100%.loss`[h] <- length(which(a == 0))
      loss.table$`100%.loss.sp`[h] <- paste(gsub("PP\\/|\\.PP|\\.tif|SSI|SDM","",gsub("_"," ",colnames(a[which(a == 0)]))), collapse=', ')
      loss.table$`90%.loss`[h] <- length(which(a > 0 & a <= 0.1))
      loss.table$`90%.loss.sp`[h] <- paste(gsub("PP\\/|\\.PP|\\.tif|SSI|SDM","",gsub("_"," ",colnames(a[which(a > 0 & a <= 0.1)]))), collapse=', ')
      loss.table$`75%.loss`[h] <- length(which(a > 0.1 & a <= 0.25))
      loss.table$`75%.loss.sp`[h] <- paste(gsub("PP\\/|\\.PP|\\.tif|SSI|SDM","",gsub("_"," ",colnames(a[which(a > 0.1 & a <= 0.25)]))), collapse=', ')
      loss.table$`50%.loss`[h] <- length(which(a > 0.25 & a <= 0.5))
      loss.table$`50%.loss.sp`[h] <- paste(gsub("PP\\/|\\.PP|\\.tif|SSI|SDM","",gsub("_"," ",colnames(a[which(a > 0.25 & a <= 0.5)]))), collapse=', ')
    
      plot(curves$Prop_landscape_lost,curves$ave_prop_rem,type="l",main=loss.table[h,1])
        lines(curves$Prop_landscape_lost,curves$min_prop_rem,lty=2)
        abline(v=cleared,col="red")
    
    })
  }

  loss.table <- loss.table[order(loss.table$order),]
  
  loss.table$protected.areas <- conflict.table$prop.protected[conflict.table$scenario %in% loss.table$scenario]
  loss.table$priority.areas <- conflict.table$prop.top[conflict.table$scenario %in% loss.table$scenario]
  
  # output table with individual species impacts for each scenario
  write.csv(distribution.table, paste0(output_path, 'tables/CL_distribution.impacts_',analysis.date,'.csv'), row.names=F)

```


```{r link to horrenda table}
# load horrenda table
  protected.species <- read.csv(paste0(computer,"/GIS_data/Perth-Peel/species data/WA listed protected species.csv"))
  
  # impacted.species <- data.frame(scenario=NA,distribution.loss=NA,Biodiversity.Feature=NA,Common.Name=NA,Taxa=NA,MNES=NA,WA.Status=NA,EPBC.Status=NA,Endemism=NA,Data.Type=NA)

 impacted.species <- data.frame(scenario=NA,distribution.loss=NA,species=NA,common.name=NA,taxa=NA,mnes=NA,wa.status=NA,epbc.status=NA,endemism=NA,data.type=NA)  
 
  extract.sp.attributes <- function(species){
    sp.data <- protected.species[protected.species$Scientific.Name==species,]
    
    mnes <- ifelse(!is.na(sp.data$mnes),"TRUE","")
    data.type <- as.character(sp.data$datatype)
    taxa <- sp.data$Taxa
      taxa <- gsub('Tec','TEC',gsub("\\b(\\w)","\\U\\1",gsub("s","",taxa), perl=TRUE))
    common.name <- ifelse(!is.null(sp.data$AcceptedCommonName),as.character(sp.data$AcceptedCommonName), "")
    wa.status <-  as.character(sp.data$WA_Status)
      wa.status <- gsub("not listed in WA|no status listed|unknown", "", wa.status)
    epbc.status <- as.character(sp.data$EPBC_Status)
      epbc.status <- gsub("not listed under the EPBC Act|no status listed|unknown", "", epbc.status)
    epbc.marine <- ifelse(as.character(sp.data$EPBC_ListedMarine)=="yes","Marine","")
    epbc.mig <- ifelse(as.character(sp.data$EPBC_ListedMigratory)=="yes","Marine","")
    epbc.status <- paste(epbc.status, epbc.marine, epbc.mig, sep=",")
    endemism <- as.character(sp.data$Endemism)
    
    output <- cbind(species,common.name,taxa,mnes,wa.status,epbc.status,endemism,data.type)
      output <- lapply(output, function(y) gsub("Critically Endangered", "CE", y))
      output <- lapply(output, function(y) gsub("Endangered", "E", y))
      output <- lapply(output, function(y) gsub("Vulnerable", "V", y))
      output <- lapply(output, function(y) gsub('([,])\\1+', ", ", gsub('^,*|,*$',"", y)))
      output <- as.data.frame(output)
      colnames(output) <- c("species","common.name","taxa","mnes","wa.status","epbc.status","endemism","data.type")
    return(output)
  }
  
  extract.lost.sp <- function(data,scenario,loss.range){
    output <- data.frame(scenario=NA,distribution.loss=NA,species=NA,common.name=NA,taxa=NA,mnes=NA,wa.status=NA,epbc.status=NA,endemism=NA,data.type=NA) 
    
    loss.data <- data[,c(scenario,"species")]
    
    for(i in seq(loss.range)){
    
      if(loss.range[i]==0){
        lost.species <- loss.data[loss.data[1]==loss.range[i],]
      } else {
        lost.species <- loss.data[(loss.data[1]>loss.range[i-1] & loss.data[1]<=loss.range[i]),]
        }
        if(nrow(lost.species)!=0) {
          for(k in seq(lost.species$species)){
            species <- clean.names(lost.species$species[k])
            species.data <- cbind(scenario=scenario, distribution.loss=ifelse(loss.range[i]==0,"100%",paste0(">",(1-loss.range[i])*100,"%")), extract.sp.attributes(species))
            output <- rbind(output,species.data)
          }
        }
    }
    output <- output[complete.cases(output),]
    return(output)
  }

  for(i in seq(loss.files)){
   impacted.species <- rbind(impacted.species,extract.lost.sp(distribution.table,scenario = loss.files[i],loss.range = c(0,0.1,0.25,0.5)))
  }
  
 # tidy impacted species table
   impacted.species <- impacted.species[complete.cases(impacted.species),]
   colnames(impacted.species) <- c("Scenario","%.Distribution.Loss","Biodiversity.Feature","Common.Name","Taxa","MNES","WA.Status","EPBC.Status","Endemism","Data.Type")
 
 write.csv(impacted.species, paste0(output_path, 'tables/TableF2_CL_impacted_species_',analysis.date,'.csv'), row.names=F)

```


```{r calculate values for special species}
# files <- gsub(paste0("_",analysis.date,'.CAZ_ME.curves.txt'),"",grep(paste0(analysis.date,'.CAZ_ME.curves.txt'), list.files(output_path), value=T))

# create table for species of interest
  special.sp.table <- d(scenario=loss.table$scenario, cleared.ha=loss.table$area.cleared.ha, cleared=loss.table$area.cleared, mean.loss=loss.table$`mean.loss(%)`, Calyptorhynchus_latirostris=NA, cbc.feeding=NA, Drakaea_elastica=NA, Caladenia_huegelii=NA, Conospermum_undulatum=NA, Pseudocheirus_occidentalis=NA, "Limestone_ridges_(SCP_26a)"=NA, EPA_Biodiversity3_10pct=NA, EPA_Biodiversity3_30pct=NA, mask.layer=loss.table$mask.layer, fraction=NA)

  colnames(special.sp.table) <- c("scenario","cleared.ha","cleared","mean.loss","Calyptorhynchus_latirostris","cbc.feeding","Drakaea_elastica","Caladenia_huegelii","Conospermum_undulatum","Pseudocheirus_occidentalis","Limestone_ridges_(SCP_26a)","EPA_Biodiversity3_10pct","EPA_Biodiversity3_30pct","mask.layer","fraction")

  special.sp.table$fraction <- special.sp.table$cleared/100
  
  sp.col <- 4:(ncol(special.sp.table)-2)
  
  for(i in seq(special.sp.table$scenario)){
    cat("Calculating special feature distributions in",as.character(special.sp.table$scenario[i]),"\n")
    
    input <- paste0(output_path, "CL.",special.sp.table$mask.layer[i],"_",analysis.date,".CAZ_ME.curves.txt")
      input <- gsub('CL.CL_','CL.',input)
  
  #  if(grepl("baseline",special.sp.table$scenario[i])==TRUE) input<- gsub("ME","",input)

  # Upload the curves file
    curves <- read.table(input, skip=1, header=F, sep='')
    colnames(curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', gsub(" ","_",clean.names(names)))
    sp.curves <- curves[,names(curves) %in% names(special.sp.table[sp.col])]
      sp.curves <- data.frame('Prop_landscape_lost'=curves$Prop_landscape_lost,sp.curves)
      sp.curves <- sp.curves[sp.curves$Prop_landscape_lost>=special.sp.table$fraction[i],][1,]
      sp.curves <- sp.curves[,c('Prop_landscape_lost',"Calyptorhynchus_latirostris","cbc.feeding","Drakaea_elastica","Caladenia_huegelii","Conospermum_undulatum","Pseudocheirus_occidentalis","Limestone_ridges_.SCP_26a.","EPA_Biodiversity3_10pct","EPA_Biodiversity3_30pct")]
      
    special.sp.table[i,sp.col] <- (1- sp.curves[,-1])*100
      
  }

  write.csv(special.sp.table,paste0(output_path,"tables/special.sp.table_",analysis.date,".csv"),row.names=F)

  
  # subset special sp.table for Figure 4
  
  Fig4_table <- special.sp.table[,c("scenario","cleared","mean.loss","Caladenia_huegelii","Drakaea_elastica","Calyptorhynchus_latirostris","Pseudocheirus_occidentalis","Conospermum_undulatum","cleared.ha")]
    Fig4_table <- Fig4_table[Fig4_table$scenario %in% c("Cumulative V1","Cumulative V2","Cumulative V3","7. Cumulative"),]
    Fig4_table <- Fig4_table[order(Fig4_table$cleared.ha,decreasing = T),]
    
  write.csv(Fig4_table,paste0(output_path,"tables/Figure4_special.sp.table_",analysis.date,".csv"),row.names=F)

```


```{r save image}
 save.image(paste0(output_path,"Analysis of Zonation runs from ",analysis.date,".Rdata"))

```

This doesn't work




```{r identify biodiversity features in runs}

# species <- gsub(".tif","",gsub("_"," ",names))
# 
# # number of features
# length(species)
# 
# mnes.species <- species[species %in% protected.species$Scientific.Name[protected.species$mnes==TRUE]]
#   mnes.species <- append(mnes.species,c("Swift Parrot","Regent Honeyeater",species[grep("Nominated",species)]))
# 
# birds <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="birds"]]
# #   birds <- append(birds,c("Swift Parrot","Regent Honeyeater"))
# 
# amphibians <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="amphibians"]]
# mammals <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="mammals"]]
# plants <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="plants"]]
# reptiles <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="reptiles"]]
# invertebrates <- species[species %in% protected.species$Scientific.Name[protected.species$Taxa=="invertebrates"]]
# tecs <- species[!species %in% protected.species$Scientific.Name]
# #   tecs <- tecs[!tecs %in% c("ghff foraging","ghff roosting","koala rawhabval6","Regent Honeyeater","Swift Parrot")]
# sdm.species <- species[species %in% protected.species$Scientific.Name[protected.species$LH.sdm=="SDM"]]
#   
# 
# cat("Total features:",length(names),"\n","MNES:",length(mnes.species),"\n", "amphibians:",length(amphibians),"\n","invertebrates:",length(invertebrates),"\n","birds:",length(birds),"\n","mammals:",length(mammals),"\n","plants:",length(plants),"\n","reptiles:",length(reptiles),"\n","tecs:",length(tecs),"\n","SDM:",length(sdm.species)+7)

```

