---
title: "Figures for CL Strategic Framework paper"
author: "Amy Whitehead"
date: "Friday, November 14, 2014"
output: html_document
---


```{r set up}
  rm(list=ls())
  library(raster)
  library(maptools)
  library(colorRamps)
  library(fields)
  library(RColorBrewer)

  GDA94.50 <- CRS("+proj=utm +zone=50 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

  # computer <- "~"
  # computer <- "//654cw-20990/Amy"
  # computer <- "Z:/Amy"
  computer <- "E:/Super Computer Data"
  
  # define paths for input and output files
  input_path <- paste0(computer,'/GIS_data/Perth-Peel/zonation/100m/Conservation_Letters/final/')
  output_path <- paste0(input_path,'output/')

# date of the output files
#   analysis.date <- '20140728' # remember to update to correct date
  analysis.date <- '20160112'

  save.plots <- TRUE
  plot.pdf <- TRUE
  plot.png <- TRUE

  scenario.files <- dir(paste0(input_path,"scenarios/"),pattern=".tif$",full.names=T)
  
  PP.mask <- raster(paste0(computer,"/GIS_Data/Perth-Peel/mask files/perth.mask.tif"))
  PP.clipping.mask <- raster(paste0(computer,"/GIS_Data/Perth-Peel/mask files/perth.clipping.mask.tif"))
  PP.shp <- readShapePoly(paste0(computer,"/GIS_data/Perth-Peel/mask files/DoP_StrategicAssessmentStudyBoundary_Extended_20121004_GDA94.shp"), proj4=GDA94)
    PP.shp <- spTransform(PP.shp,GDA94.50)
  
  zonation_priority <- raster(paste0(output_path,"CL.baseline_",analysis.date,".CAZ_E.rank.compressed.tif"))
  top30 <- zonation_priority
    top30[top30<0.7] <- NA
  
  scenario.files <- dir(paste0(input_path,"scenarios/"),pattern=".tif$",full.names=T)
    scenarios <- stack(scenario.files)

```

```{r colour palettes}
map.background <- "whitesmoke"

pa.colours <- d(label=c("Level 3","Level 2","Level 1","Priority protected","Priority unprotected", "Phase 1", "Phase 2"), colour=c("#78c679", "#31a354", "#006837", "#a6611a", "grey40", "#003399", "#6699FF"), stringsAsFactors = F)

dev.colours <- data.frame(label=c("Existing","Proposed","Cleared","Retained"),colour=c("grey60","#fdae61","#d7191c","#2c7bb6"),stringsAsFactors = F)

# colours for the curves plots - Heini
# col.all <- c('dark grey', 'skyblue2', 'skyblue4', 'darkolivegreen3', 'darkolivegreen4')
# col.nonmnes <- c('lightskyblue4', 'skyblue2', 'steelblue', 'dodgerblue3', 'dodgerblue4')
# col.mnes <- c('rosybrown4', 'lightcoral', 'indianred', 'brown1', 'red4')

# colours for the curves plots - Amy
col.all <- c("grey60",brewer.pal(4,"Set1"))
col.nonmnes <- brewer.pal(9,"Blues")[4:9]
col.mnes <- brewer.pal(9,"Reds")[4:9]

pri.col = c('blue', 'turquoise', 'yellow', 'orange', 'red')
pri.col = c('dark grey', 'turquoise', 'yellow', 'orange', 'red')
pa.col = c('palegreen2','palegreen3', 'palegreen4')
pri.breaks = c(0,0.7,0.85,0.9,0.95,1)
leg.labels <- c("top 5%","top 10%","top 15%","top 30%","rest")

```

```{r cumulative development, echo=FALSE}
  dev.cum <- scenarios[[which(names(scenarios) %in% "scenario7_cumulative"==TRUE)]]
  
  r <- dev.cum
    r[r>2] <- NA
    r[!is.na(r)] <-1
  dev.pri <- mask(zonation_priority,r)
 
  
  png(paste0(output_path,"figures/cumulative_development_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
       par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
       plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(dev.pri,col=c("grey30",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
        plot(PP.shp, add=T, lwd=0.5)
      legend('topright', inset=c(-0.250,0), leg.labels, col="black",fill=rev(pri.col), bty="n", title=paste0("Conservation priority","\n","within development zones"), cex=1, xpd=NA)
  dev.off()
  
  
  png(paste0(output_path,"figures/cumulative_development.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
       par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
       plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(dev.cum,col="grey30",zlim=c(2,2),legend=F,add=T)
        plot(PP.shp, add=T, lwd=0.5)
  dev.off()
  
  png(paste0(output_path,"figures/conservation_priority.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
       par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
       plot(zonation_priority,col=pri.col,breaks=pri.breaks,legend=F,axes=F,box=F)
        plot(PP.shp, add=T, lwd=0.5)
      legend('topright', inset=c(-0.250,0), leg.labels, col="black",fill=rev(pri.col), bty="n", title="Conservation priority", cex=1, xpd=NA)
  dev.off()
  
  
  png(paste0(output_path,"figures/priority_development_conflict.png"),height=10,width=15,units="cm",res=300, bg="transparent",pointsize=12)
    par(mfrow=c(1,3),mar=c(4.5,0.25,1.25,0.5), oma=c(0,0,0,0))
      
      plot(zonation_priority,col=pri.col,breaks=pri.breaks,legend=F,axes=F,box=F)
        plot(PP.shp, add=T, lwd=0.5)
        mtext("a)",side=3,line=-0.5,adj=0,cex=0.8)
   
      plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(dev.cum,col="grey30",zlim=c(2,2),legend=F,add=T)
        plot(PP.shp, add=T, lwd=0.5)
        mtext("b)",side=3,line=-0.5,adj=0,cex=0.8)
  
  legend('bottom', inset=c(0,-0.18), c(leg.labels,"Development"), col="black",fill=c(rev(pri.col),"grey30"), bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=T,title.adj = 0)
      
      plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(dev.pri,col=c("grey30",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
        plot(PP.shp, add=T, lwd=0.5)
        mtext("c)",side=3,line=-0.5,adj=0,cex=0.8)
          
  dev.off()
  
  
  png(paste0(output_path,"figures/priority_conflict.png"),height=15,width=15,units="cm",res=300, bg="transparent",pointsize=10)
    par(mfrow=c(1,2),mar=c(4.5,0.25,1.25,0.5), oma=c(0,0,0,0))
      
      plot(zonation_priority,col=pri.col,breaks=pri.breaks,legend=F,axes=F,box=F)
        plot(PP.shp, add=T, lwd=0.5)
        mtext("a)",side=3,line=-0.5,adj=0)
  
  legend('bottomleft', inset=c(0,-0.15), c(leg.labels,"Development"), col="black",fill=c(rev(pri.col),"grey30"), bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=T,title.adj = 0)
      
      plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(dev.pri,col=c("grey30",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
        plot(PP.shp, add=T, lwd=0.5)
        mtext("b)",side=3,line=-0.5,adj=0)
          
  dev.off()

```

```{r Figure 2 - priority conflict inset maps}
# interest.points <- data.frame(x=c(414801.7, 423401.2, 404332.6, 392368.0),y=c(6497004, 6479057, 6426712, 6391192))
# interest.points <- data.frame(x=c(383394.5, 423775.1, 383016.2, 397850.3),y=c(6497378, 6478683, 6429329, 6389553))
  
  interest.points <- data.frame(x=c(409049.9,401813.3,383016.2, 394650.3),y=c(6499173,6442093,6429329, 6389553))

#png(paste0(output_path,"figures/priority_conflict_insets_v2.png"),height=14,width=17.5,units="cm",res=300, bg="transparent",pointsize=10)
#lay.out <- matrix(c(1,1,1,1,1,2,2,2,2,2,3,4,5,6,7),5,3,byrow=F)
#layout(lay.out,widths = c(0.4,0.4,0.2))

# png(paste0(output_path,"figures/Figure2.png"),height=14,width=17.3,units="cm",res=300, bg="transparent",pointsize=10)
pdf(paste0(output_path,"figures/Figure2.pdf"),height=140*0.0393700787,width=173*0.0393700787,pointsize=10)
lay.out <- layout(matrix(c(1,1,1,1,1,2,2,2,2,2,3,4,5,6,7),5,3,byrow=F),widths = c(0.4,0.4,0.2))


# png(paste0(output_path,"figures/priority_conflict_insets_v2_part1.png"),height=14,width=14,units="cm",res=300, bg="transparent",pointsize=10)

# par(mfrow=c(1,2), mar=c(0,0,0,0), oma=c(0,0.5,0,0))
    

    # plot(zonation_priority,col=c("grey",pri.col[2:5]),breaks=pri.breaks,legend=F,axes=F,box=F)
      # plot(PP.shp, add=TRUE, lwd=0.5)

    image(zonation_priority,col=c("grey",pri.col[2:5]),breaks=pri.breaks,ann=F,axes=F)
      plot(PP.shp, add=T, lwd=0.5)

      mtext("A",side=3,line=-1.5,adj=0, font=2)
      scalebar(10000,xy=c(444785.1-15000,6357750),type="line",label = "10 km")
   
    image(zonation_priority,col=map.background,ann=F,axes=F)
     image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,zlim=c(0,1))
#       plot(zonation_priority,col=c("grey",pri.col[2:5]),breaks=pri.breaks,legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
      mtext("B",side=3,line=-1.5,adj=0, font=2)

      text(x=interest.points$x[1],y=interest.points$y[1],"1",font = 2,cex=1.5)
      text(x=interest.points$x[2],y=interest.points$y[2],"2",font = 2,cex=1.5)
      text(x=interest.points$x[3],y=interest.points$y[3],"3",font = 2,cex=1.5)
      text(x=interest.points$x[4],y=interest.points$y[4],"4",font = 2,cex=1.5)
# dev.off()
# 
# png(paste0(output_path,"figures/priority_conflict_insets_v2_part2.png"),height=14,width=3.5,units="cm",res=300, bg="transparent",pointsize=10)
# 
# par(mfrow=c(5,1), mar=c(1,1,1,1)) 
# =======
#       text(x=interest.points$x[1],y=interest.points$y[1],"1",font = 2,cex=1.75)
#       text(x=interest.points$x[2],y=interest.points$y[2],"2",font = 2,cex=1.75)
#       text(x=interest.points$x[3],y=interest.points$y[3],"3",font = 2,cex=1.75)
#       text(x=interest.points$x[4],y=interest.points$y[4],"4",font = 2,cex=1.75)
    
  par(mar=c(1,1,1,1)) 

  image(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(interest.points$x[1]-6000,interest.points$x[1]+6000),ylim=c(interest.points$y[1]-6000,interest.points$y[1]+6000),asp=1)

    image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,asp=1)
    plot(PP.shp, add=T, lwd=0.5)
    box()
    mtext("1",side=3,line=-1.5,adj=0.05)

  image(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(interest.points$x[2]-6000,interest.points$x[2]+6000),ylim=c(interest.points$y[2]-6000,interest.points$y[2]+6000),asp=1)
    image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,asp=1)
    plot(PP.shp, add=T, lwd=0.5)
    box()
    mtext("2",side=3,line=-1.5,adj=0.05)

  image(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(interest.points$x[3]-6000,interest.points$x[3]+6000),ylim=c(interest.points$y[3]-6000,interest.points$y[3]+6000),asp=1)
    image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,asp=1)
    plot(PP.shp, add=T, lwd=0.5)
    box()
    mtext("3",side=3,line=-1.5,adj=0.05)

  image(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(interest.points$x[4]-6000,interest.points$x[4]+6000),ylim=c(interest.points$y[4]-6000,interest.points$y[4]+6000),asp=1)
    image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,asp=1)
    box()
    mtext("4",side=3,line=-1.5,adj=0.05)
  scalebar(5000,xy=c(interest.points$x[4]-6000,interest.points$y[4]-5500),type="line",label = "5 km")

  plot(dev.pri,col=NA,box=F,legend=F,axes=F)
 
  legend('left', inset=c(0,0), c(leg.labels), col="black",fill=c(rev(pri.col[2:5]),"grey"), bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=F,title.adj = 0)

dev.off()

```

```{r identify development in Fig 2 boxes}

  scenario.files <- dir(paste0(input_path,"scenarios/"),pattern=".tif$",full.names=T)
    scenario.files <- scenario.files[grepl("urban|industrial|rural|infrastructure|pines|brm",scenario.files)]
    scenario.files <- scenario.files[!grepl("no.existing",scenario.files)]
    scenario.files <- scenario.files[grepl("clipped",scenario.files)]
  scenarios <- stack(scenario.files)
  scenario.names <- names(scenarios)
  
  output <- as.data.frame(matrix(NA,nrow=nrow(interest.points),ncol=length(scenario.names)+1))
    names(output) <- c("Box",scenario.names)
      
  for(i in 1:nrow(interest.points)){
    interest.extent <- extent(interest.points$x[i]-6000,interest.points$x[i]+6000,interest.points$y[i]-6000,interest.points$y[i]+6000)
    output$Box[i] <- i
    cat(paste0("Box ",i,":","\n"))
    
    for(j in seq(scenario.names)){
      s <- scenarios[[j]]
      s <- crop(s,interest.extent)
      ncells <- length(s[s<3])/length(s[!is.na(s)])
      output[i,j+1] <- round(ncells,3)
      cat(paste0(" ",scenario.names[j],"\n"))
    }
  }

```


```{r EIA iterations}

eia1 <- raster(paste0(input_path,"scenarios/CL_EIA1.tif"))
  r <- eia1
  r[r!=2] <- NA
  r[!is.na(r)] <-1
eia1.pri <- merge(r*zonation_priority,r*-1)

eia2 <- raster(paste0(input_path,"scenarios/CL_EIA2.tif"))
  r <- eia2
  r[r!=2] <- NA
  r[!is.na(r)] <-1
eia2.pri <- merge(r*zonation_priority,r*-1)

eia3o1 <- raster(paste0(input_path,"scenarios/CL_EIA3O1.tif"))
  r <- eia3o1
  r[r!=2] <- NA
  r[!is.na(r)] <-1
eia3o1.pri <- merge(r*zonation_priority,r*-1)

eia3o2 <- raster(paste0(input_path,"scenarios/CL_EIA3O2.tif"))
  r <- eia3o2
  r[r!=2] <- NA
  r[!is.na(r)] <-1
eia3o2.pri <- merge(r*zonation_priority,r*-1)

cur.dev <- raster(paste0(input_path,"scenarios/scenario3_development.footprint.tif"))
  r <- cur.dev
  r[r!=2] <- NA
  r[!is.na(r)] <-1
cur.dev.pri <- merge(r*zonation_priority,r*-1)

png(paste0(output_path,"eia1_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
     par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
     plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
      plot(eia1.pri,col=c(NA,pri.col[2:5]),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)

dev.off()


png(paste0(output_path,"eia2_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
    par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))     
    plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
      plot(eia2.pri,col=c(NA,pri.col[2:5]),breaks=c(pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
dev.off()

png(paste0(output_path,"eia3O1_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
    par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
    plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
      plot(eia3o1.pri,col=c(NA,pri.col[2:5]),breaks=c(pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
dev.off()

png(paste0(output_path,"eia3O2_conflicts.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
     par(mar=c(0.25,1.5,1.25,2), oma=c(0,0,0,0))
     
  plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
      plot(eia3o2.pri,col=c("grey30",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
dev.off()



# Grey-Red color

png(paste0(output_path,"eia1_conflicts_redgrey.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
plot(PP.shp, add=T, lwd=0.5)
plot(eia1 == 2, col=c(NA, 'dark grey'), legend=F, add=T)
plot((eia1 == 2)*pri.30, col=c(NA, 'red'), legend=F, add=T)
#plot(PP.shp, add=T, lwd=0.5)
dev.off()

png(paste0(output_path,"eia2_conflicts_redgrey.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
plot(PP.shp, add=T, lwd=0.5)
plot(eia2 == 2, col=c(NA, 'dark grey'), legend=F, add=T)
plot((eia2 == 2)*pri.30, col=c(NA, 'red'), legend=F, add=T)
dev.off()

png(paste0(output_path,"eia3o2_conflicts_redgrey.png"),height=20,width=15,units="cm",res=300, bg="transparent",pointsize=14)
plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
plot(PP.shp, add=T, lwd=0.5)
plot(eia3o2 == 2, col=c(NA, 'dark grey'), legend=F, add=T)
plot((eia3o2 == 2)*pri.30, col=c(NA, 'red'), legend=F, add=T)
dev.off()


```

```{r combined EIA plots}

distribution.table <- read.csv(paste0(output_path, '/CL_distribution.impacts_',analysis.date,'.csv'))
  distribution.table$change <- (distribution.table[,"CL_eia3O2_20140924.CAZ_ME.curves.txt"]-distribution.table[,"CL_eia1_20140924.CAZ_ME.curves.txt"])/distribution.table[,"CL_eia1_20140924.CAZ_ME.curves.txt"]

png(paste0(output_path,"eia_conflicts&impacts.png"),height=22,width=12,units="cm",res=300, bg="transparent",pointsize=14)
 pl<- layout(matrix(c(1,2,3,4,5,5),3,2,byrow=T))  
par(mar=c(0.25,0.5,1.25,0.5),las=1)
     
  plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(eia1.pri,col=c("grey50",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)

plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(eia2.pri,col=c("grey50",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)

plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(eia3o1.pri,col=c("grey50",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)

plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
     plot(eia3o2.pri,col=c("grey50",pri.col),breaks=c(-1,pri.breaks),legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)

par(mar=c(4,6,1.25,2))
boxplot(1-distribution.table[,grepl("eia",colnames(distribution.table))],horizontal=T,xlab="Proportion of distributions lost",names=c("EIA1","EIA2","EIA3O1","EIA3O2"))

dev.off()

```

```{r D2031-GGP urban comparison}
 
D2031 <- raster(paste0(input_path,"scenarios/D2031_UrbanExpansion.tif"))
GGP <- raster(paste0(input_path,"scenarios/GGP_UrbanExpansion.tif"))
GGP.NRZ <- raster(paste0(input_path,"scenarios/GGP_UrbanExpansion_NoRetentionZones.tif"))

# identify retention zones
RZ <- GGP - GGP.NRZ
RZ[RZ==-2] <- 4
RZ[RZ!=4] <- NA

plotConflictT30 <- function(myRaster){
    #myRaster <- GGP.NRZ
    myRaster[myRaster==3] <- NA
    myRasterT30 <- sum(myRaster,top30)
    myRasterT30 <- merge(myRasterT30,myRaster)
    names(myRasterT30) <- paste(names(myRaster),"T30")
    return(myRasterT30)
}
D2031.pri <- plotConflictT30(D2031)

GGP.pri <- plotConflictT30(GGP)
GGP.RZ.pri <- merge(RZ,GGP.pri)

inset_location <- c(390362,6393628)
box.coordinates <- c(inset_location[1]-8500,inset_location[1]+8500,inset_location[2]-8500,inset_location[2]+8500)

# png(paste0(output_path,"figures/D2031-GGP_top30_conflicts.png"),height=15,width=20,units="cm",res=300, bg="transparent",pointsize=14)

svg(paste0(output_path,"figures/D2031-GGP_top30_conflicts.svg"),width = 15,height=15,bg = "transparent")


  par(mfrow=c(1,2),mar=c(0.25,0.25,1.5,0.25), oma=c(0,0,0,0))
  plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
    plot(D2031.pri,col=c(dev.colours$colour[1],"red"),legend=F,add=T)
    plot(PP.shp, add=T, lwd=0.5)
    rect(box.coordinates[1],box.coordinates[3],box.coordinates[2],box.coordinates[4])
    # mtext("a) Directions 2031", side=3,line=0,adj=0)
    
  plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
    plot(GGP.RZ.pri,col=c(dev.colours$colour[1],"red","black"),legend=F,add=T)
    plot(PP.shp, add=T, lwd=0.5)
    rect(box.coordinates[1],box.coordinates[3],box.coordinates[2],box.coordinates[4])

    # mtext("b) Green Growth Plan", side=3,line=0,adj=0)
  
dev.off()



svg(paste0(output_path,"figures/D2031_GGP_inset.svg"),width = 10,height=5,bg = "transparent")
par(mfrow=c(1,2),mar=c(0,0.5,0,0.5))
plot(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(box.cordinates[1:2]),ylim=c(box.cordinates[3:4]),asp=1)

    plot(D2031.pri,col=c(dev.colours$colour[1],"red"),ann=F,add=T,asp=1,legend=F,xlim=c(box.cordinates[1:2]),ylim=c(box.cordinates[3:4]))
    plot(PP.shp, add=T, lwd=0.5)
    box()
    
plot(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(box.cordinates[1:2]),ylim=c(box.cordinates[3:4]),asp=1)

    plot(GGP.RZ.pri,col=c(dev.colours$colour[1],"red","black"),ann=F,add=T,asp=1,xlim=c(box.cordinates[1:2]),ylim=c(box.cordinates[3:4]))
    plot(PP.shp, add=T, lwd=0.5)
    box()
dev.off()

svg(paste0(output_path,"figures/D2031_inset.svg"),width = 5,height=5,bg = "transparent")
par(mfrow=c(1,1),mar=c(0.5,0.5,0.5,0.5))    
plot(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(box.coordinates[1:2]),ylim=c(box.coordinates[3:4]),asp=1,legend=F,box=F)

    plot(D2031.pri,col=c(dev.colours$colour[1],"red"),ann=F,add=T,asp=1,legend=F,xlim=c(box.coordinates[1:2]),ylim=c(box.coordinates[3:4]))
    # plot(PP.shp, add=T, lwd=0.5)
    rect(box.coordinates[1],box.coordinates[3],box.coordinates[2],box.coordinates[4])
dev.off()

svg(paste0(output_path,"figures/GPP.RZ_inset.svg"),width = 5,height=5,bg = "transparent")
par(mfrow=c(1,1),mar=c(0.5,0.5,0.5,0.5))    
plot(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(box.coordinates[1:2]),ylim=c(box.coordinates[3:4]),asp=1,legend=F,box=F)

    plot(GGP.RZ.pri,col=c(dev.colours$colour[1],"red","black"),ann=F,add=T,asp=1,legend=F,xlim=c(box.coordinates[1:2]),ylim=c(box.coordinates[3:4]))
    # plot(PP.shp, add=T, lwd=0.5)
    rect(box.coordinates[1],box.coordinates[3],box.coordinates[2],box.coordinates[4])
dev.off()

# png(paste0(output_path,"figures/D2031-GGP_top30_conflicts_inset.png"),height=15,width=20,units="cm",res=300, bg="transparent",pointsize=14)
# lay.out <- layout(matrix(c(1,1,1,1,1,2,2,2,2,2,3,4,5,6,7),5,3,byrow=F),widths = c(0.4,0.4,0.2))
# 
#   # par(mfrow=c(1,2),mar=c(0.25,0.25,1.5,0.25), oma=c(0,0,0,0))
#   plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
#     plot(D2031.pri,col=c(dev.colours$colour[1],"red"),legend=F,add=T)
#     plot(PP.shp, add=T, lwd=0.5)
#     mtext("a) Directions 2031", side=3,line=0,adj=0)
#     
#   plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
#     plot(GGP.RZ.pri,col=c(dev.colours$colour[1],"red","black"),legend=F,add=T)
#     plot(PP.shp, add=T, lwd=0.5)
#     mtext("b) Green Growth Plan", side=3,line=0,adj=0)
#   
# dev.off()

```


```{r map of study region}

AU <- shapefile(paste0(computer,"/GIS_data/Australia/australia_one polygon.shp"))
  AU <- spTransform(AU,GDA94.50)

ibra.shp <- readShapePoly(paste0(computer,"/GIS_data/Perth-Peel/environmental data/PP_IBRA.shp")) 

png(paste0(output_path,"PPSA_study_area.png"),height=14,width=17.5,units="cm",res=300, bg="transparent",pointsize=10)
lay.out <- layout(matrix(c(1,1,1,2,3,4),3,2,byrow=F),widths = c(0.8,0.2))

par(mar=c(0,0,0,0), oma=c(0,0.5,0,0),xpd=TRUE)
    
    plot(ibra.shp)  
      image(PP.clipping.mask,col="darkgreen",legend=F,add=T)
      plot(AU,add=T,lwd=0.5,border="grey")
      plot(ibra.shp,add=T)
      points(392867.8,6460059,pch=16,cex=1)
      plot(PP.shp, add=T, lwd=0.5)
      scalebar(50000,xy=c(444785.1-15000,6257750),type="line",label = "")

 
  plot(AU,xlim=c(88778.64,4635700),ylim=c(5957750,8774441),add=T)
    plot(ibra.shp,add=T)
    image(PP.clipping.mask,col="darkgreen",legend=F,add=T)

    

dev.off()



lay.out <- layout(matrix(c(1,1,1,1,1,2,2,2,2,2,3,4,5,6,7),5,3,byrow=F),widths = c(0.4,0.4,0.2))

par(mar=c(0,0,0,0), oma=c(0,0.5,0,0))
    
    plot(zonation_priority,col=c("grey",pri.col[2:5]),breaks=pri.breaks,legend=F,axes=F,box=F)
      plot(PP.shp, add=T, lwd=0.5)
      mtext("A",side=3,line=-1.5,adj=0, font=2)
      scalebar(10000,xy=c(444785.1-15000,6357750),type="line",label = "10 km")
   
    plot(zonation_priority,col=map.background,legend=F,box=F,axes=F)
      plot(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),legend=F,add=T,zlim=c(0,1))
#       plot(zonation_priority,col=c("grey",pri.col[2:5]),breaks=pri.breaks,legend=F,add=T)
      plot(PP.shp, add=T, lwd=0.5)
      mtext("B",side=3,line=-1.5,adj=0, font=2)
      text(x=interest.points$x[1],y=interest.points$y[1],"1",font = 2,cex=1.5)
      text(x=interest.points$x[2],y=interest.points$y[2],"2",font = 2,cex=1.5)
      text(x=interest.points$x[3],y=interest.points$y[3],"3",font = 2,cex=1.5)
      text(x=interest.points$x[4],y=interest.points$y[4],"4",font = 2,cex=1.5)
    
  par(mar=c(1,1,1,1)) 
  image(PP.clipping.mask,col=map.background,ann=F,axes=F,xlim=c(interest.points$x[1]-6000,interest.points$x[1]+6000),ylim=c(interest.points$y[1]-6000,interest.points$y[1]+6000),asp=1)

    image(dev.pri,col=c("grey",pri.col[2:5]),breaks=c(pri.breaks),ann=F,add=T,asp=1)
    box()
    mtext("1",side=3,line=-1.5,adj=0.05)

```

```{r boxplot of species impacts}
  sp.impacts <- read.csv(paste0(output_path,"tables/CL_distribution.impacts_",analysis.date,".csv"))
    sp.impacts[1:(ncol(sp.impacts)-1)] <- 1- sp.impacts[1:(ncol(sp.impacts)-1)]
    sp.impacts <- sp.impacts[,names(sp.impacts) %in% c("species",paste0("CL.",c("scenario1_urban","scenario2_industrial","scenario3_ruralres","scenario4_infrastructure","scenario5_pines","scenario6_brm","scenario7_cumulative"),"_",analysis.date,".CAZ_ME.curves.txt"))]

  development <- c(names(sp.impacts[1:(ncol(sp.impacts)-1)]))
  dev.label <- c("1. Urban","2. Industrial","3. Rural residential","4. Infrastructure","5. Forestry", "6. Mining", "7. Cumulative")

  # png(paste0(output_path,"figures/Figure3.png"),height=62,width=82,units="mm",bg="transparent",pointsize=9,res=600)
  pdf(paste0(output_path,"figures/Figure3.pdf"),height=62*0.0393700787,width=82*0.0393700787,pointsize=10)
    par(las=1,mar=c(4,8,1,1),oma=c(0,0,0,0),lwd=0.5)
    boxplot(sp.impacts[,c(development[7:1])],names=dev.label[12:6],horizontal = T,xlab=paste0("Proportion of feature distributions","\n","lost to development"), yaxt="n",xaxt="n",lwd=0.5)
      axis(2,labels=F,lwd=0.5)
      axis(1,labels=c("0.00","0.25","0.50","0.75","1.00"),at=seq(0,1,by=0.25),lwd=0.5)
      text(x=-0.85,y=seq_along(dev.label[1:7]),labels=dev.label[7:1],xpd=NA,adj=0)
  dev.off()

```


```{r Figure E1 - protected priorities}
  
    pa.protected.areas <- scenarios[["protected_areas"]]
    pa.protected.areas.clipped <- scenarios[["protected_areas_clipped"]]

    pa.protected.areas.plot <- pa.protected.areas
      pa.protected.areas.plot[pa.protected.areas.plot==3] <- 0
      pa.protected.areas.plot[pa.protected.areas.plot!=0] <- 1
  
    pa.protected.priorities <- merge(mask(pa.protected.areas.plot + zonation_priority,top30),pa.protected.areas)

    png(paste0(output_path,"figures/Figure_D1_protected_areas.png"),height=14,width=17.5,units="cm",res=300, bg="transparent",pointsize=10)
      par(mfrow=c(1,2),mar=c(0,0,0,2), oma=c(0,0,0,3),xpd=NA)
      
      plot(PP.clipping.mask,col="whitesmoke",legend=F,box=F,axes=F)
        plot(pa.protected.areas,col=pa.colours$colour[1:3],add=T,legend=F,zlim=c(4,6))
        plot(PP.shp, add=T, lwd=0.5)
      leg.labels <- c("High", "Medium", "Low") 
      legend("topright",inset=c(-0.25,0.575),xjust=1,leg.labels,col=rev(pa.colours$colour[1:3]),pch=15,bty="n",title=paste0("Existing","\n","Protected Areas"),cex=1,xpd=NA)
      mtext("A",side=3,line=-1,adj=0, font=2)
  
      plot(PP.clipping.mask,col="whitesmoke",legend=F,box=F,axes=F)
        plot(pa.protected.priorities,add=T,col=c(NA,pri.col[2:5],"grey50",NA,"grey70"),breaks=c(0,0.7,0.85,0.9,0.95,1,2,4,6),legend=F)
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","Protected priorities", "Protected areas") 
      legend("topright",inset=c(-0.35,0.575),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),"grey50", "grey70"),pch=15,bty="n",title="Conservation priority",cex=1,xpd=NA)
      mtext("B",side=3,line=-1,adj=0, font=2)
    dev.off()

```


```{r Figure E2 - protected priorities & conservation reserves}
    conservation.reserves <-  readShapePoly( paste0(computer, "/GIS_data/Perth-Peel/CoA/DPaw_proposed_conservation_reserves/DPaW_Proposed_GGP_Conservation_Reserves_20160316.shp"))
      proj4string(conservation.reserves) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
      conservation.reserves <- spTransform(conservation.reserves, CRS("+proj=utm +zone=50 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
    
    cr.protected.areas <- scenarios[["high_protected_areas_conservation_reserves"]]
    cr.protected.areas.clipped <- scenarios[["high_protected_areas_conservation_reserves_clipped"]]

    cr.protected.areas.plot <- cr.protected.areas
      cr.protected.areas.plot[cr.protected.areas.plot==3] <- 0
      cr.protected.areas.plot[cr.protected.areas.plot!=0] <- 1
      
    cr.protected.areas.bkg <- merge(cr.protected.areas,PP.clipping.mask)
  
    cr.protected.priorities <- merge(mask(cr.protected.areas.plot + zonation_priority,top30),cr.protected.areas)

    png(paste0(output_path,"figures/Figure_D2_high_protected_areas_conservation_reserves.png"),height=14,width=17.5,units="cm",res=300, bg="transparent",pointsize=10)
      par(mfrow=c(1,2),mar=c(0,0,0,2), oma=c(0,0,0,3),xpd=NA)
      
      plot(cr.protected.areas.bkg,col=c(map.background,pa.colours$colour[c(7,6,3)]),legend=F,box=F,axes=F,zlim=c(3,6))
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Existing High", "Phase 1", "Phase 2") 
      legend("topright",inset=c(-0.35,0.575),xjust=1,leg.labels,col=rev(pa.colours$colour[c(7,6,3)]),pch=15,bty="n",title=paste0("Proposed","\n"," Conservation Reserves"),cex=1,xpd=NA)
      mtext("A",side=3,line=-1,adj=0, font=2)
  
      plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(cr.protected.priorities,add=T,col=c(NA,pri.col[2:5],"grey50",NA,"grey70"),breaks=c(0,0.7,0.85,0.9,0.95,1,2,4,6),legend=F)
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","Protected priorities", "Protected areas") 
      legend("topright",inset=c(-0.35,0.575),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),"grey50", "grey70"),pch=15,bty="n",title="Conservation priority",cex=1,xpd=NA)
      mtext("B",side=3,line=-1,adj=0, font=2)
    dev.off()

```

```{r combined PA-CR plot}
    
    png(paste0(output_path,"figures/Figure_D3_CR-PA.png"),height=28,width=17.5,units="cm",res=300, bg="transparent",pointsize=10)
      par(mfrow=c(2,2),mar=c(2,1,2,2), oma=c(0,0,0,3),xpd=NA)
      
      plot(PP.clipping.mask,col="whitesmoke",legend=F,box=F,axes=F)
        plot(pa.protected.areas,col=pa.colours$colour[1:3],add=T,legend=F,zlim=c(4,6))
        plot(PP.shp, add=T, lwd=0.5)
      leg.labels <- c("High", "Medium", "Low") 
      legend("topright",inset=c(-0.15,0.575),xjust=1,leg.labels,col=rev(pa.colours$colour[1:3]),pch=15,bty="n",title=paste0("Existing","\n","Protected Areas"),cex=1,xpd=NA)
      mtext("A) Existing Protected Areas",side=3,line=1,adj=0, font=2)
  
      plot(PP.clipping.mask,col="whitesmoke",legend=F,box=F,axes=F)
        plot(pa.protected.priorities,add=T,col=c(NA,pri.col[2:5],"grey50",NA,"grey70"),breaks=c(0,0.7,0.85,0.9,0.95,1,2,4,6),legend=F)
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","Protected priorities", "Protected areas") 
      legend("topright",inset=c(-0.3,0.575),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),"grey50", "grey70"),pch=15,bty="n",title="Conservation priority",cex=1,xpd=NA)
      # mtext("B",side=3,line=-1,adj=0, font=2)
      
      plot(cr.protected.areas.bkg,col=c(map.background,pa.colours$colour[c(7,6,3)]),legend=F,box=F,axes=F,zlim=c(3,6))
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Existing High", "Phase 1", "Phase 2") 
      legend("topright",inset=c(-0.25,0.575),xjust=1,leg.labels,col=rev(pa.colours$colour[c(7,6,3)]),pch=15,bty="n",title=paste0("Proposed","\n"," Conservation Reserves"),cex=1,xpd=NA)
      mtext("B) Proposed Conservation Reserves",side=3,line=1,adj=0, font=2)
  
      plot(PP.clipping.mask,col=map.background,legend=F,box=F,axes=F)
        plot(cr.protected.priorities,add=T,col=c(NA,pri.col[2:5],"grey50",NA,"grey70"),breaks=c(0,0.7,0.85,0.9,0.95,1,2,4,6),legend=F)
        plot(PP.shp, add=T, lwd=0.5)
        
      leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","Protected priorities", "Protected areas") 
      legend("topright",inset=c(-0.3,0.575),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),"grey50", "grey70"),pch=15,bty="n",title="Conservation priority",cex=1,xpd=NA)
      # mtext("D",side=3,line=-1,adj=0, font=2)
    dev.off()

```


```{r create raster function}
create.raster <- function (s, mask.raster, raster.label, value, transform=TRUE, save=TRUE, plot=TRUE) {
    
   if(transform==TRUE) {
     proj4string(s) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
    s <- spTransform(s, CRS("+proj=utm +zone=50 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
     }
    
  r <- rasterize(s,mask.raster)
    r[!is.na(r)] <- value
    r <- mask(merge(r,mask.raster),mask.raster)
    
    names(r) <- rep(raster.label,length(names(r)))
    
    if(save==TRUE) writeRaster(r,filename=paste0(output.directory,raster.label), format="GTiff", overwrite=T)
    
    if(plot==TRUE) plot(r, main=raster.label, zlim=c(1,6))

    return(r)
  }

```

```{r E1 - proposed CR expansion}
  # load ibra mask to use as initial extent
    ibra.mask <- raster(paste0(computer,"/GIS_data/Perth-Peel/mask files/pp_ibra_mask.tif"))
  
  # load proposed conservation reserves and convert to raster
    conservation.reserves <-  readShapePoly( paste0(computer, "/GIS_data/Perth-Peel/CoA/DPaw_proposed_conservation_reserves/DPaW_Proposed_GGP_Conservation_Reserves_20160316.shp"))
      proj4string(conservation.reserves) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
      conservation.reserves <- spTransform(conservation.reserves, CRS("+proj=utm +zone=50 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
    
    CR.phase1.raster <- create.raster(conservation.reserves[conservation.reserves$PRPhase=="Phase 1",], ibra.mask,  raster.label="CR_phase1", value=5, save = FALSE,transform = F)
      CR.phase1.raster[CR.phase1.raster==0] <- NA
    
    CR.phase2.raster <- create.raster(conservation.reserves[conservation.reserves$PRPhase=="Phase 2",], ibra.mask, raster.label="CR_phase2", value=4, save=FALSE,transform = F)
      CR.phase2.raster[CR.phase2.raster==0] <- NA
      
  # load existing high security protected areas and convert to raster    
    iucn1_4a <- readShapePoly(paste0(computer, "/GIS_data/Perth-Peel/CoA/Conservation_Package_Release_Web_March2016/DPaW_ExistingConsRes_IUCN1a_4_20150630.shp"))
    iucn1_4a.raster <- create.raster(iucn1_4a, ibra.mask, raster.label = "DPaW_ExistingConsRes_IUCN1a_4_20150630", value=6,transform=T,save=F)
      iucn1_4a.raster[iucn1_4a.raster==0] <- NA
      
    PP.clipping.mask.ibra <- resample(PP.clipping.mask,ibra.mask)
      PP.clipping.mask.ibra[PP.clipping.mask.ibra==1] <- 3
    
  # merge all layers together &  crop to the extent of the CR
    pa.cr.ibra.raster <- merge(iucn1_4a.raster,CR.phase1.raster,CR.phase2.raster,PP.clipping.mask.ibra)
    
    pa.cr.raster <- crop(pa.cr.ibra.raster,extent(conservation.reserves))

    png(paste0(output_path,"figures/Figure_E1_proposed_conservation_reserves.png"),height=14,width=10,units="cm",res=300, bg="transparent",pointsize=10)
      par(mfrow=c(1,1),mar=c(0,0,0,0), oma=c(0,0,0,0),xpd=NA)
      
      plot(pa.cr.raster,col=c(map.background,pa.colours$colour[c(7,6,3)]),legend=F,box=F,axes=F,zlim=c(3,6))
        plot(PP.shp, add=T, lwd=1.5)
        
      leg.labels <- c("Existing High", "Phase 1", "Phase 2") 
      legend("topright",inset=c(-0.15,0.05),xjust=1,leg.labels,col=rev(pa.colours$colour[c(7,6,3)]),pch=15,bty="n",title=paste0("Proposed","\n"," Conservation Reserves"),cex=1,xpd=NA)
      
    dev.off()
    
```

